### PR TITLE
Fix safeParse error on reply validation

### LINKED ISSUE #3: Response validation failing with 'safeParse' is not a function
Seems to require `jsonShorthand: false` option on the server to work as expected.
Somehow [getSchemaAnyway](https://github.com/fastify/fastify/blob/cdc1114a4da0bb03c39e1e97518673dfd8edc8fa/lib/schemas.js#L113) is called and unless `jsonShorthand` is set to `false` it wraps the schema into
```json
{
  "type": "object",
  "properties": [ZodSchema]
}
```
instead of the expected bare schema

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #3

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -90,7 +90,8 @@ export const validatorCompiler: FastifySchemaCompiler<ZodAny> =
 export const serializerCompiler: FastifySerializerCompiler<ZodAny> =
   ({ schema }) =>
   (data) => {
-    const result = schema.safeParse(data);
+    // @ts-ignore
```
Comment (rupert-mckay) [inline src/index.ts:93]: ❓

What's the type error here? If it is unavoidable, we should add a comment in code here to justify it for future readers.

File: src/index.ts [hunk 2]
```diff
@@ -87,9 +87,26 @@ export const validatorCompiler: FastifySchemaCompiler<ZodAny> =
...
+  if (hasOwnProperty(maybeSchema, 'properties')) {
+    return maybeSchema.properties;
+  }
+  throw new Error(`Invalid schema passed: ${JSON.stringify(maybeSchema)}`);
+}
+
+export const serializerCompiler: FastifySerializerCompiler<ZodAny | { properties: ZodAny }> =
+  ({ schema: maybeSchema }) =>
   (data) => {
+    const schema: Pick<ZodAny, 'safeParse'> = resolveSchema(maybeSchema);
```
Comment (kibertoad) [inline src/index.ts:108]: for some reason on replies we receive ZodAny wrapped inside an additional object, and that was breaking things. Now we handle both scenarios

File: src/index.ts (hunk 1 above)
Comment (kibertoad) [reply src/index.ts]: tried to tinker something up, please check

File: src/index.ts (hunk 2 above)
Comment (alxarch) [reply src/index.ts:108]: IIRC response schemas are a map of statusCode => schema, thus the extra depth.

Comment (kibertoad) [reply src/index.ts:108]: thaaaaaat explains it

**Comment by kibertoad** [comment]
@turkerdev Can you please take a look?

**Comment by turkerdev** [comment]
> @turkerdev Can you please take a look?

I am not at home currently, let me take a look when i get home, probably 2 days later.

File: src/index.ts [hunk 3]
```diff
@@ -87,9 +87,26 @@ export const validatorCompiler: FastifySchemaCompiler<ZodAny> =
...
+
+function resolveSchema(maybeSchema: ZodAny | { properties: ZodAny }): Pick<ZodAny, 'safeParse'> {
+  if (hasOwnProperty(maybeSchema, 'safeParse')) {
+    return maybeSchema;
+  }
+  if (hasOwnProperty(maybeSchema, 'properties')) {
+    return maybeSchema.properties;
+  }
+  throw new Error(`Invalid schema passed: ${JSON.stringify(maybeSchema)}`);
+}
```
Comment (alxarch) [inline src/index.ts:103]: Relying on `properties` being present restricts schemas to objects only. It should be possible to return any type of value (i.e. array, string, boolean, number and object).

Comment (kibertoad) [reply src/index.ts:103]: I'll add a test for this case, thanks

Comment (kibertoad) [reply src/index.ts:103]: From my understanding status code may or may not be a part of zod schema, it is entirely up to whoever is designing structure of reply payload.

I've updated test suite for this change, and defining schema as a `z.string` actually seems to work perfectly fine. What doesn't work is defining schema as an object, and then returning primitive instead - since fastify won't invoke serializer at all in such case, we are not getting to validate anything. But that's a separate problem, see https://github.com/turkerdev/fastify-type-provider-zod/pull/15

Within the context of the original problem, I believe we are solving it correctly, and it should behave not worse or better than before.

Please check new tests, maybe I missed something there :)

**Comment by kibertoad** [comment]
@alxarch Where does
```
    200: z.object({
       status: z.kiteral("OK"),
       ...
   }),
   500: z.object({
       status: z.literal("ERROR"),
       error: z.object({...}),
       ...
   }),
```
come from? Reply structure can be pretty much anything

**Comment by alxarch** [comment]
> z.object({
>        status: z.literal("ERROR"),
>        error: z.object({...}),
>        ...
>    }),

If you take a look at the docs [here](
https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#serializer-compiler)
It seems that this form is needed to be able to have separate validation based on status code.

The `serializerCompiler` in the current form of the code does not take `statusCode` parameter into account.
AFAICT in order to be compatible with the default JSON Schema behavior, the `serializerCompiler` must pick the correct  schema value from a `{[statusCode string|number]: ZodTypeAny}` in `schema.response`. At least that's how I solved it in a local workaround experiment a few weeks back.

**Comment by kibertoad** [comment]
@alxarch I'm not seeing this. Example that fastify is giving is this:

```
  schema: {
    response: {
      '2xx': {
        id: { type: 'number' },
        name: { type: 'string' }
      }
    }
  }
```

there is no statusCode present here, it seems to be exactly what we are currently using.

`httpStatus` is something that serializer is receiving from fastify, and I think it should already be passed. What would you do differently than what we do now based on this documentation?

**Comment by alxarch** [comment]
I was referring to the `httpStatus` in the `setSerializerCompiler` signature. Let me check out the branch and will get back to you after I compare it to my workaround. I might have used a different approach in my experiment that is not relevant to how it is being solved here.
```js

fastify.setSerializerCompiler(({ schema, method, url, httpStatus }) => {
  return data => JSON.stringify(data)
 })
```

**Comment by kibertoad** [comment]
```
fastify.setSerializerCompiler(({ schema, method, url, httpStatus }) => {
  return data => JSON.stringify(data)
 })
```

Doesn't this completely bypass any validation?

**Review by turkerdev — APPROVED** [review]

**Comment by kibertoad** [comment]
@turkerdev Thank you! Can you publish a new version now?

**Comment by alxarch** [comment]
@kibertoad  tried the released version and it seems to work as intended! :tada:  Sorry for any confusion I might have caused.
